//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// LinuxMain.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

#if os(Linux) || os(FreeBSD)
   @testable import MustacheTests
   XCTMain([
         testCase(BoxTests.allTests),
         testCase(BoxValueTests.allTests),
         testCase(ConfigurationBaseContextTests.allTests),
         testCase(ConfigurationContentTypeTests.allTests),
         testCase(ConfigurationExtendBaseContextTests.allTests),
         testCase(ConfigurationTagDelimitersTests.allTests),
         testCase(ContextRegisteredKeyTests.allTests),
         testCase(ContextTests.allTests),
         testCase(ContextValueForMustacheExpressionTests.allTests),
         testCase(EachFilterTests.allTests),
         testCase(FilterTests.allTests),
         testCase(FormatterTests.allTests),
         //testCase(FoundationCollectionTests.allTests),
         testCase(HookFunctionTests.allTests),
         testCase(KeyedSubscriptFunctionTests.allTests),
         testCase(LambdaTests.allTests),
         testCase(LocalizerTests.allTests),
         testCase(LoggerTests.allTests),
         testCase(MustacheBoxDocumentationTests.allTests),
         testCase(MustacheBoxTests.allTests),
         testCase(MustacheRenderableGuideTests.allTests),
         testCase(ReadMeTests.allTests),
         testCase(RenderFunctionTests.allTests),
         testCase(StandardLibraryTests.allTests),
         testCase(TagTests.allTests),
         testCase(TemplateRepositoryBundleTests.allTests),
         testCase(TemplateRepositoryDataSourceTests.allTests),
         testCase(TemplateRepositoryDictionaryTests.allTests),
         testCase(TemplateRepositoryPathTests.allTests),
         testCase(TemplateRepositoryTests.allTests),
         testCase(TemplateRepositoryURLTests.allTests),
         testCase(TemplateTests.allTests),
         testCase(VariadicFilterTests.allTests),
    ])
#endif
